In [19]:
import pandas as pd
import numpy as np

In [58]:
splits = {'train': 'fluorescence_train.csv', 'validation': 'fluorescence_valid.csv', 'test': 'fluorescence_test.csv'}
df = pd.DataFrame()
for split in splits:
    df2 = pd.read_csv("hf://datasets/proteinea/fluorescence/" + splits[split])
    df2["split"] = split
    if split == "validation":
        df2["split"] = "valid"
    df = pd.concat([df, df2], ignore_index = True)

In [59]:
df

,primary,protein_length,log_fluorescence,num_mutations,split
0,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,237,3.823701,2,train
1,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,237,3.752084,2,train
2,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGRLTLKFI...,237,3.753380,2,train
3,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDANYGKLTLKFI...,237,3.752505,1,train
4,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,237,3.576366,3,train
...,...,...,...,...,...
54020,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,237,3.624042,4,test
54021,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,237,3.648814,4,test
54022,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,237,3.703998,4,test
54023,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,237,3.592672,5,test
54024,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,237,3.792052,4,test

In [60]:
df2 = pd.DataFrame(
    {
        'ID': np.arange(len(df)),
        "Sequence": df["primary"],
        "label": df["log_fluorescence"],
        "split": df["split"]
    }
)

df2

,ID,Sequence,label,split
0,0,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.823701,train
1,1,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.752084,train
2,2,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGRLTLKFI...,3.753380,train
3,3,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDANYGKLTLKFI...,3.752505,train
4,4,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.576366,train
...,...,...,...,...
54020,54020,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.624042,test
54021,54021,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.648814,test
54022,54022,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.703998,test
54023,54023,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.592672,test
54024,54024,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.792052,test

In [41]:
df2.columns

Index(['ID', 'Sequence', 'label', 'split'], dtype='object')

In [61]:
df2['ID'] = df2['ID'].apply(lambda x: f"P{int(x):05d}")

In [62]:
df2

,ID,Sequence,label,split
0,P00000,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.823701,train
1,P00001,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.752084,train
2,P00002,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGRLTLKFI...,3.753380,train
3,P00003,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDANYGKLTLKFI...,3.752505,train
4,P00004,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.576366,train
...,...,...,...,...
54020,P54020,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.624042,test
54021,P54021,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.648814,test
54022,P54022,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.703998,test
54023,P54023,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.592672,test
54024,P54024,SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFI...,3.792052,test

In [65]:
df2.to_csv("/scratch/PLM/datasets/fluorescence_data.csv", index=False)